version: '3'

services:
    common-tests:
        image: event-application-form-common
        build: './common'

    backend-tests:
        build: './backend'
        volumes:
            - ./backend:/app/backend
            - /app/backend/node_modules
            - /app/backend/common
        depends_on:
            - common-tests
        command: npm test

    frontend-tests:
        build: './frontend'
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
            - /app/frontend/common
        depends_on:
            - common-tests
        command: npm test
