version: '3'

services:
    backend-tests:
        build:
            context: ./
            dockerfile: ./backend/Dockerfile
            args:
                task: test
        volumes:
            - ./backend:/app/backend

    frontend-tests:
        build:
            context: ./
            dockerfile: ./frontend/Dockerfile
            args:
                task: test
        volumes:
            - ./frontend:/app/frontend
